site_name: Fabric Wiki 中文翻译文档

theme:
    name: readthedocs

markdown_extensions:
    - admonition
    - codehilite:
          guess_lang: false
          linenums: false
    - toc:
          permalink: true
    - footnotes
    - meta
    - def_list

nav:
    - 开始 [Fabric Wiki]: index.md
    - '常见问题':
          - '常见问题（用户）': 'faq/faq_user.md'
          - '常见问题（专家）': 'faq/faq_expert.md'
    - 'Mod开发者':
        - '世界生成':
            - '在世界中生成自定义矿石': 'modev/worldgen/ores.md'